export const SECTION_LABELS: Record<string, string> = {
  astronomical: "Astronomical",
  alos: "Alos HaShachar (Dawn)",
  misheyakir: "Misheyakir",
  sunrise: "Sunrise (Netz HaChama)",
  sofZmanShema: "Sof Zman Shema (Latest Shema)",
  sofZmanTefila: "Sof Zman Tefila (Latest Tefila)",
  chatzos: "Chatzos (Halachic Noon / Midnight)",
  minchaGedola: "Mincha Gedola",
  minchaKetana: "Mincha Ketana",
  plagHamincha: "Plag HaMincha",
  sunset: "Sunset (Shkiah)",
  beinHashmashos: "Bein HaShmashos",
  tzait: "Tzait HaKochavim (Nightfall)",
  shaahZmanis: "Shaah Zmanis (Halachic Hour)",
  chametz: "Chametz (Pesach)",
  kidushLevana: "Kidush Levana",
};

export const ZMAN_LABELS: Record<string, string> = {
  // Astronomical
  sunrise: "Sunrise",
  seaLevelSunrise: "Sea Level Sunrise",
  sunset: "Sunset",
  seaLevelSunset: "Sea Level Sunset",
  sunTransit: "Solar Noon (True)",
  solarMidnight: "Solar Midnight",
  beginAstronomicalTwilight: "Begin Astronomical Twilight",
  endAstronomicalTwilight: "End Astronomical Twilight",
  beginNauticalTwilight: "Begin Nautical Twilight",
  endNauticalTwilight: "End Nautical Twilight",
  beginCivilTwilight: "Begin Civil Twilight",
  endCivilTwilight: "End Civil Twilight",
  localMeanTime: "Local Mean Time (Solar)",

  // Alos
  alos72: "Alos 72 min (MGA)",
  alosHashachar: "Alos HaShachar (GRA 16.1°)",
  alos60: "Alos 60 min",
  alos90: "Alos 90 min",
  alos90Zmanis: "Alos 90 Zmanis min",
  alos96: "Alos 96 min",
  alos96Zmanis: "Alos 96 Zmanis min",
  alos120: "Alos 120 min",
  alos120Zmanis: "Alos 120 Zmanis min",
  alos72Zmanis: "Alos 72 Zmanis min",
  alos16Point1Degrees: "Alos 16.1° below horizon",
  alos18Degrees: "Alos 18° below horizon",
  alos19Degrees: "Alos 19° below horizon",
  alos19Point8Degrees: "Alos 19.8° below horizon",
  alos26Degrees: "Alos 26° below horizon",
  alosBaalHatanya: "Alos — Baal HaTanya (16.9°)",

  // Misheyakir
  misheyakir7Point65Degrees: "Misheyakir 7.65°",
  misheyakir9Point5Degrees: "Misheyakir 9.5°",
  misheyakir10Point2Degrees: "Misheyakir 10.2°",
  misheyakir11Degrees: "Misheyakir 11°",
  misheyakir11Point5Degrees: "Misheyakir 11.5°",

  // Sunrise
  "sunrise (sunrise)": "Sunrise",
  elevationAdjustedSunrise: "Elevation-Adjusted Sunrise",
  sunriseBaalHatanya: "Sunrise — Baal HaTanya (1.583°)",

  // Shema
  sofZmanShmaGRA: "Sof Zman Shema — GRA / Vilna Gaon",
  sofZmanShmaMGA: "Sof Zman Shema — MGA (72 min)",
  sofZmanShmaMGA72Minutes: "Sof Zman Shema — MGA 72 min fixed",
  sofZmanShmaMGA72MinutesZmanis: "Sof Zman Shema — MGA 72 Zmanis min",
  sofZmanShmaMGA90Minutes: "Sof Zman Shema — MGA 90 min",
  sofZmanShmaMGA90MinutesZmanis: "Sof Zman Shema — MGA 90 Zmanis min",
  sofZmanShmaMGA96Minutes: "Sof Zman Shema — MGA 96 min",
  sofZmanShmaMGA96MinutesZmanis: "Sof Zman Shema — MGA 96 Zmanis min",
  sofZmanShmaMGA120Minutes: "Sof Zman Shema — MGA 120 min",
  sofZmanShmaMGA16Point1Degrees: "Sof Zman Shema — MGA 16.1°",
  sofZmanShmaMGA18Degrees: "Sof Zman Shema — MGA 18°",
  sofZmanShmaMGA19Point8Degrees: "Sof Zman Shema — MGA 19.8°",
  sofZmanShmaAteretTorah: "Sof Zman Shema — Ateret Torah",
  sofZmanShmaBaalHatanya: "Sof Zman Shema — Baal HaTanya",
  sofZmanShmaKolEliyahu: "Sof Zman Shema — Kol Eliyahu",
  sofZmanShmaFixedLocal: "Sof Zman Shema — Fixed Local Chatzos",
  sofZmanShma3HoursBeforeChatzos: "Sof Zman Shema — 3 Hours Before Chatzos",
  sofZmanShmaAlos16Point1ToSunset: "Sof Zman Shema — Alos 16.1° to Sunset",
  sofZmanShmaAlos16Point1ToTzaisGeonim7Point083Degrees:
    "Sof Zman Shema — Alos 16.1° to Tzais Geonim 7.083°",
  sofZmanShmaGRASunriseToFixedLocalChatzos:
    "Sof Zman Shema — GRA Sunrise to Fixed Local Chatzos",
  sofZmanShmaMGA16Point1DegreesToFixedLocalChatzos:
    "Sof Zman Shema — MGA 16.1° to Fixed Local Chatzos",
  sofZmanShmaMGA72MinutesToFixedLocalChatzos:
    "Sof Zman Shema — MGA 72 min to Fixed Local Chatzos",
  sofZmanShmaMGA90MinutesToFixedLocalChatzos:
    "Sof Zman Shema — MGA 90 min to Fixed Local Chatzos",
  sofZmanShmaMGA18DegreesToFixedLocalChatzos:
    "Sof Zman Shema — MGA 18° to Fixed Local Chatzos",

  // Tefila
  sofZmanTfilaGRA: "Sof Zman Tefila — GRA / Vilna Gaon",
  sofZmanTfilaMGA: "Sof Zman Tefila — MGA (72 min)",
  sofZmanTfilaMGA72Minutes: "Sof Zman Tefila — MGA 72 min fixed",
  sofZmanTfilaMGA72MinutesZmanis: "Sof Zman Tefila — MGA 72 Zmanis min",
  sofZmanTfilaMGA90Minutes: "Sof Zman Tefila — MGA 90 min",
  sofZmanTfilaMGA90MinutesZmanis: "Sof Zman Tefila — MGA 90 Zmanis min",
  sofZmanTfilaMGA96Minutes: "Sof Zman Tefila — MGA 96 min",
  sofZmanTfilaMGA96MinutesZmanis: "Sof Zman Tefila — MGA 96 Zmanis min",
  sofZmanTfilaMGA120Minutes: "Sof Zman Tefila — MGA 120 min",
  sofZmanTfilaMGA16Point1Degrees: "Sof Zman Tefila — MGA 16.1°",
  sofZmanTfilaMGA18Degrees: "Sof Zman Tefila — MGA 18°",
  sofZmanTfilaMGA19Point8Degrees: "Sof Zman Tefila — MGA 19.8°",
  sofZmanTfilaAteretTorah: "Sof Zman Tefila — Ateret Torah",
  sofZmanTfilahAteretTorah: "Sof Zman Tefilah — Ateret Torah (alt)",
  sofZmanTfilaBaalHatanya: "Sof Zman Tefila — Baal HaTanya",
  sofZmanTfilaFixedLocal: "Sof Zman Tefila — Fixed Local Chatzos",
  sofZmanTfila2HoursBeforeChatzos: "Sof Zman Tefila — 2 Hours Before Chatzos",
  sofZmanTfilaGRASunriseToFixedLocalChatzos:
    "Sof Zman Tefila — GRA Sunrise to Fixed Local Chatzos",

  // Chatzos
  chatzos: "Chatzos (Halachic Noon)",
  chatzosAsHalfDay: "Chatzos as Half Day",
  fixedLocalChatzos: "Fixed Local Chatzos",
  midnightLastNight: "Chatzos Lailah (Last Night Midnight)",
  midnightTonight: "Chatzos Lailah (Tonight Midnight)",

  // Mincha Gedola
  minchaGedola: "Mincha Gedola (GRA)",
  minchaGedola30Minutes: "Mincha Gedola 30 min after Chatzos",
  minchaGedola72Minutes: "Mincha Gedola — MGA 72 min",
  minchaGedola16Point1Degrees: "Mincha Gedola 16.1°",
  minchaGedolaGreaterThan30: "Mincha Gedola — Greater of GRA/30 min",
  minchaGedolaAhavatShalom: "Mincha Gedola — Ahavat Shalom",
  minchaGedolaAteretTorah: "Mincha Gedola — Ateret Torah",
  minchaGedolaBaalHatanya: "Mincha Gedola — Baal HaTanya",
  minchaGedolaBaalHatanyaGreaterThan30:
    "Mincha Gedola — Baal HaTanya (≥30 min)",
  minchaGedolaGRAFixedLocalChatzos30Minutes:
    "Mincha Gedola — GRA Fixed Local + 30 min",

  // Mincha Ketana
  minchaKetana: "Mincha Ketana (GRA)",
  minchaKetana16Point1Degrees: "Mincha Ketana 16.1°",
  minchaKetana72Minutes: "Mincha Ketana — MGA 72 min",
  minchaKetanaAhavatShalom: "Mincha Ketana — Ahavat Shalom",
  minchaKetanaAteretTorah: "Mincha Ketana — Ateret Torah",
  minchaKetanaBaalHatanya: "Mincha Ketana — Baal HaTanya",
  minchaKetanaGRAFixedLocalChatzosToSunset:
    "Mincha Ketana — GRA Fixed Local Chatzos to Sunset",
  samuchLeMinchaKetanaGRA: "Samuch LeMinhca Ketana (GRA)",
  samuchLeMinchaKetana16Point1Degrees: "Samuch LeMinchaKetana 16.1°",
  samuchLeMinchaKetana72Minutes: "Samuch LeMinchaKetana 72 min",

  // Plag
  plagHamincha: "Plag HaMincha (GRA)",
  plagHamincha60Minutes: "Plag HaMincha 60 min",
  plagHamincha72Minutes: "Plag HaMincha 72 min",
  plagHamincha72MinutesZmanis: "Plag HaMincha 72 Zmanis min",
  plagHamincha90Minutes: "Plag HaMincha 90 min",
  plagHamincha90MinutesZmanis: "Plag HaMincha 90 Zmanis min",
  plagHamincha96Minutes: "Plag HaMincha 96 min",
  plagHamincha96MinutesZmanis: "Plag HaMincha 96 Zmanis min",
  plagHamincha120Minutes: "Plag HaMincha 120 min",
  plagHamincha120MinutesZmanis: "Plag HaMincha 120 Zmanis min",
  plagHamincha16Point1Degrees: "Plag HaMincha 16.1°",
  plagHamincha18Degrees: "Plag HaMincha 18°",
  plagHamincha19Point8Degrees: "Plag HaMincha 19.8°",
  plagHamincha26Degrees: "Plag HaMincha 26°",
  plagHaminchaAteretTorah: "Plag HaMincha — Ateret Torah",
  plagHaminchaBaalHatanya: "Plag HaMincha — Baal HaTanya",
  plagAhavatShalom: "Plag — Ahavat Shalom",
  plagAlosToSunset: "Plag — Alos to Sunset",
  plagAlos16Point1ToTzaisGeonim7Point083Degrees:
    "Plag — Alos 16.1° to Tzais Geonim 7.083°",

  // Sunset
  "sunset (sunset)": "Sunset",
  elevationAdjustedSunset: "Elevation-Adjusted Sunset",
  sunsetBaalHatanya: "Sunset — Baal HaTanya",
  candleLighting: "Candle Lighting (18 min before sunset)",

  // Bein HaShmashos
  bainHashmashosRT13Point24Degrees: "Bein HaShmashos — R\"T 13.24°",
  bainHashmashosRT13Point5MinutesBefore7Point083Degrees:
    'Bein HaShmashos — R"T 13.5 min before 7.083°',
  bainHashmashosRT2Stars: 'Bein HaShmashos — R"T 2 Stars',
  bainHashmashosRT58Point5Minutes: 'Bein HaShmashos — R"T 58.5 min',
  bainHashmashosYereim13Point5Minutes: "Bein HaShmashos — Yereim 13.5 min",
  bainHashmashosYereim16Point875Minutes: "Bein HaShmashos — Yereim 16.875 min",
  bainHashmashosYereim18Minutes: "Bein HaShmashos — Yereim 18 min",
  bainHashmashosYereim2Point1Degrees: "Bein HaShmashos — Yereim 2.1°",
  bainHashmashosYereim2Point8Degrees: "Bein HaShmashos — Yereim 2.8°",
  bainHashmashosYereim3Point05Degrees: "Bein HaShmashos — Yereim 3.05°",

  // Tzait
  tzais: "Tzait (GRA 8.5°)",
  tzais72: "Tzait 72 min (R\"T / Rabbeinu Tam)",
  tzais72Zmanis: "Tzait 72 Zmanis min",
  tzais50: "Tzait 50 min",
  tzais60: "Tzait 60 min",
  tzais90: "Tzait 90 min",
  tzais90Zmanis: "Tzait 90 Zmanis min",
  tzais96: "Tzait 96 min",
  tzais96Zmanis: "Tzait 96 Zmanis min",
  tzais120: "Tzait 120 min",
  tzais120Zmanis: "Tzait 120 Zmanis min",
  tzais16Point1Degrees: "Tzait 16.1° (Alos HaShachar)",
  tzais18Degrees: "Tzait 18° (Night / Lailah)",
  tzais19Point8Degrees: "Tzait 19.8°",
  tzais26Degrees: "Tzait 26°",
  tzaisAteretTorah: "Tzait — Ateret Torah",
  tzaisBaalHatanya: "Tzait — Baal HaTanya",
  tzaisGeonim3Point65Degrees: "Tzait Geonim 3.65°",
  tzaisGeonim3Point676Degrees: "Tzait Geonim 3.676°",
  tzaisGeonim3Point7Degrees: "Tzait Geonim 3.7°",
  tzaisGeonim3Point8Degrees: "Tzait Geonim 3.8°",
  tzaisGeonim4Point37Degrees: "Tzait Geonim 4.37°",
  tzaisGeonim4Point61Degrees: "Tzait Geonim 4.61°",
  tzaisGeonim4Point8Degrees: "Tzait Geonim 4.8°",
  tzaisGeonim5Point88Degrees: "Tzait Geonim 5.88°",
  tzaisGeonim5Point95Degrees: "Tzait Geonim 5.95°",
  tzaisGeonim6Point45Degrees: "Tzait Geonim 6.45°",
  tzaisGeonim7Point083Degrees: "Tzait Geonim 7.083°",
  tzaisGeonim7Point67Degrees: "Tzait Geonim 7.67°",
  tzaisGeonim8Point5Degrees: "Tzait Geonim 8.5°",
  tzaisGeonim9Point3Degrees: "Tzait Geonim 9.3°",
  tzaisGeonim9Point75Degrees: "Tzait Geonim 9.75°",

  // Shaah Zmanis
  shaahZmanisGra: "Shaah Zmanis — GRA (Sunrise to Sunset)",
  shaahZmanisMGA: "Shaah Zmanis — MGA (Alos 72 min to Tzait 72 min)",
  shaahZmanis60Minutes: "Shaah Zmanis — 60 min Alos/Tzait",
  shaahZmanis72Minutes: "Shaah Zmanis — 72 min",
  shaahZmanis72MinutesZmanis: "Shaah Zmanis — 72 Zmanis min",
  shaahZmanis90Minutes: "Shaah Zmanis — 90 min",
  shaahZmanis90MinutesZmanis: "Shaah Zmanis — 90 Zmanis min",
  shaahZmanis96Minutes: "Shaah Zmanis — 96 min",
  shaahZmanis96MinutesZmanis: "Shaah Zmanis — 96 Zmanis min",
  shaahZmanis120Minutes: "Shaah Zmanis — 120 min",
  shaahZmanis120MinutesZmanis: "Shaah Zmanis — 120 Zmanis min",
  shaahZmanis16Point1Degrees: "Shaah Zmanis — 16.1°",
  shaahZmanis18Degrees: "Shaah Zmanis — 18°",
  shaahZmanis19Point8Degrees: "Shaah Zmanis — 19.8°",
  shaahZmanis26Degrees: "Shaah Zmanis — 26°",
  shaahZmanisAteretTorah: "Shaah Zmanis — Ateret Torah",
  shaahZmanisBaalHatanya: "Shaah Zmanis — Baal HaTanya",
  shaahZmanisAlos16Point1ToTzais3Point7: "Shaah Zmanis — Alos 16.1° to Tzais 3.7°",
  shaahZmanisAlos16Point1ToTzais3Point8: "Shaah Zmanis — Alos 16.1° to Tzais 3.8°",

  // Chametz
  sofZmanAchilasChametzGRA: "Sof Zman Achilas Chametz — GRA",
  sofZmanAchilasChametzMGA72Minutes: "Sof Zman Achilas Chametz — MGA 72 min",
  sofZmanAchilasChametzMGA72MinutesZmanis: "Sof Zman Achilas Chametz — MGA 72 Zmanis",
  sofZmanAchilasChametzMGA16Point1Degrees: "Sof Zman Achilas Chametz — MGA 16.1°",
  sofZmanAchilasChametzBaalHatanya: "Sof Zman Achilas Chametz — Baal HaTanya",
  sofZmanBiurChametzGRA: "Sof Zman Biur Chametz — GRA",
  sofZmanBiurChametzMGA72Minutes: "Sof Zman Biur Chametz — MGA 72 min",
  sofZmanBiurChametzMGA72MinutesZmanis: "Sof Zman Biur Chametz — MGA 72 Zmanis",
  sofZmanBiurChametzMGA16Point1Degrees: "Sof Zman Biur Chametz — MGA 16.1°",
  sofZmanBiurChametzBaalHatanya: "Sof Zman Biur Chametz — Baal HaTanya",

  // Kidush Levana
  tchilasZmanKidushLevana3Days: "Tchila Kidush Levana — 3 Days",
  tchilasZmanKidushLevana7Days: "Tchila Kidush Levana — 7 Days",
  sofZmanKidushLevana15Days: "Sof Zman Kidush Levana — 15 Days",
  sofZmanKidushLevanaBetweenMoldos: "Sof Zman Kidush Levana — Between Moldos",
  zmanMolad: "Zman HaMolad",
};
